# Generated by Django 5.2 on 2025-09-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_mode', models.CharField(choices=[('local', 'LOCAL'), ('api', 'API SIGENU'), ('api_uho', 'API UHO')], default='local', max_length=10)),
            ],
            options={
                'db_table': 'authentication_settings',
            },
        ),
    ]
