# Generated by Django 4.2.16 on 2025-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vicerrector', 'Vicerrector'), ('Jefe_departamento', 'Jefe de departamento'), ('Jefe_area', 'Jefe de area'), ('Investigador', 'Investigador')], default='Seleccione...', max_length=50),
        ),
    ]
