# Generated by Django 4.2.16 on 2025-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vicerrector', 'Vicerrector'), ('Jefe_departamento', 'Jefe de departamento'), ('Jefe_area', 'Jefe de area'), ('Investigador', 'Investigador')], default='Investigador', max_length=20, verbose_name='Rol de Usuario'),
        ),
    ]
