# Generated by Django 4.2.16 on 2025-05-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
