# Generated by Django 5.2.3 on 2025-06-28 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_mode', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
