# Generated by Django 4.2.16 on 2025-04-09 11:32

from django.db import migrations, models
import django.db.models.deletion
import investigador.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9)),
                ('doi', models.CharField(max_length=9)),
                ('fecha_creacion', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('pais', models.CharField(choices=[('Cuba', 'Cuba'), ('Otro', 'Otro')], default='Seleccione...', max_length=50)),
                ('isbn', models.CharField(max_length=10)),
                ('capitulo', models.CharField(max_length=10)),
                ('volumen', models.CharField(max_length=10)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('fecha_create', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_cientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_cientifica', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_docente', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracter', models.CharField(choices=[('Congreso', 'Congreso'), ('Jornada', 'Jornada'), ('Foro', 'Foro'), ('Conferencia', 'Conferencia'), ('Panel', 'Panel'), ('Simposio', 'Simposio'), ('Mesa Redonda', 'Mesa Redonda'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Convencion', 'Convencion'), ('Encuentro', 'Encuentro')], default='Seleccione...', max_length=50)),
                ('tipo', models.CharField(choices=[('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Seleccione...', max_length=50)),
                ('presencialidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixto', 'Mixto')], default='Seleccione...', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=10)),
                ('publicacion', models.URLField(null=True)),
                ('fecha', models.DateField()),
                ('certificado', models.FileField(upload_to='Eventos/')),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('fecha_create', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('cargo', models.CharField(max_length=100)),
                ('orci', models.CharField(max_length=10)),
                ('google_academico', models.URLField(verbose_name='')),
                ('rgate', models.URLField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('premiados', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('caracter_premio', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Forum Ciencia Tecnica}', 'Forum Ciencia Tecnica'), ('Forum Nacionales Estudiantiles', 'Forum Nacionales Estudiantiles'), ('Jornadas Cientificas Estudiantiles', 'Jornadas Cientificas Estudiantiles')], default='Seleccione...', max_length=50)),
                ('tipo', models.CharField(choices=[('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Seleccione...', max_length=50)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('fecha_create', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programa', models.CharField(blank=True, max_length=36)),
                ('nombre_programa', models.CharField(max_length=255)),
                ('jefe_programa', models.CharField(max_length=150)),
                ('sector_estrategico', models.CharField(choices=[('Sector productor de alimentos', 'Sector productor de alimentos'), ('Industria Ligera', 'Industria Ligera'), ('Servicios técnicos profesionales', 'Servicios técnicos profesionales'), ('Industria', 'Industria'), ('Agroindustria azucarera y sus derivados', 'Agroindustria azucarera y sus derivados'), ('Industria farmacéutica, biotecnológica y', 'Industria farmacéutica, biotecnológica y'), ('Turismo', 'Turismo'), ('Logística integrada de redes e instalaciones', 'Logística integrada de redes e instalaciones'), ('Logística integrada de transporte', 'Logística integrada de transporte'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Electroenergético', 'Electroenergético'), ('Construcciones', 'Construcciones')], max_length=100)),
                ('linea_investigacion', models.CharField(choices=[('Línea 1', 'Línea de Investigación 1'), ('Línea 2', 'Línea de Investigación 2'), ('Línea 3', 'Línea de Investigación 3')], max_length=100)),
                ('cantidad_expertos_contratados', models.IntegerField()),
                ('cantidad_expertos_uho', models.IntegerField()),
                ('cantidad_expertos_otras_entidades', models.IntegerField()),
                ('cantidad_proyectos_programa', models.IntegerField()),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=10)),
                ('fecha_create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(blank=True, max_length=36)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('jefe_proyecto', models.CharField(max_length=150)),
                ('tipo_proyecto', models.CharField(choices=[('PAPN', 'Proyectos Asociados a Programas Nacionales'), ('PAPS', 'Proyectos Asociados a Programas Sectoriales'), ('PAPT', 'Proyectos Asociados a Programas Territoriales'), ('PNAP', 'Proyectos No Asociados a Programas')], max_length=50)),
                ('subtipo_proyecto', models.CharField(blank=True, choices=[('PI', 'Proyectos Institucionales'), ('PE', 'Proyectos Empresariales'), ('PNE', 'Proyectos con Entidades No Empresariales y de la Administración Pública'), ('PDL', 'Proyectos de Desarrollo Local'), ('PRCI', 'Proyectos en Relación con la Colaboración Internacional')], max_length=50, null=True)),
                ('entidades_participantes', models.TextField(max_length=150)),
                ('sector_estrategico', models.CharField(choices=[('Sector productor de alimentos', 'Sector productor de alimentos'), ('Industria Ligera', 'Industria Ligera'), ('Servicios técnicos profesionales', 'Servicios técnicos profesionales'), ('Industria', 'Industria'), ('Agroindustria azucarera y sus derivados', 'Agroindustria azucarera y sus derivados'), ('Industria farmacéutica, biotecnológica y', 'Industria farmacéutica, biotecnológica y'), ('Turismo', 'Turismo'), ('Logística integrada de redes e instalaciones', 'Logística integrada de redes e instalaciones'), ('Logística integrada de transporte', 'Logística integrada de transporte'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Electroenergético', 'Electroenergético'), ('Construcciones', 'Construcciones')], max_length=100)),
                ('linea_investigacion', models.CharField(choices=[('Línea 1', 'Línea de Investigación 1'), ('Línea 2', 'Línea de Investigación 2'), ('Línea 3', 'Línea de Investigación 3')], max_length=100)),
                ('fecha_inicio', models.DateField(validators=[investigador.models.fecha_no_anterior_a_hoy])),
                ('fecha_cierre', models.DateField(validators=[investigador.models.fecha_no_anterior_a_hoy])),
                ('estado_proyecto', models.CharField(choices=[('Normal', 'Normal'), ('Atrasado', 'Atrasado'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado'), ('Prórroga', 'Prórroga')], max_length=10)),
                ('cantidad_profesores_trabajadores_uho', models.CharField(max_length=11)),
                ('cantidad_estudiantes_contratados', models.CharField(max_length=11)),
                ('cantidad_participantes_otras_entidades', models.CharField(max_length=11)),
                ('cantidad_profesores_colaboradores_uho', models.CharField(max_length=11)),
                ('cantidad_estudiantes_grupos_cientificos', models.CharField(max_length=11)),
                ('cantidad_colaboradores_otras_entidades', models.CharField(max_length=11)),
                ('cantidad_estudiantes_segundo_adelante', models.CharField(max_length=11)),
                ('cantidad_cuadros_uho', models.CharField(max_length=11)),
                ('presupuesto_planificado', models.CharField(max_length=11)),
                ('presupuesto_ejecutado_primer_semestre', models.CharField(max_length=11)),
                ('presupuesto_ejecutado_segundo_semestre', models.CharField(max_length=11)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=10)),
                ('fecha_create', models.DateField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.area')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.departamento')),
            ],
        ),
    ]
