# Generated by Django 4.2.16 on 2025-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='colaboradores',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
