# Generated by Django 4.2.16 on 2025-04-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigador', '0003_evento_colaboradores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='premiados',
        ),
        migrations.AlterField(
            model_name='premio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premio',
            name='premiados',
            field=models.ManyToManyField(related_name='premios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
