# Generated by Django 4.2.16 on 2025-04-13 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigador', '0004_remove_premio_premiados_alter_premio_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='autores',
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='autores',
            field=models.ManyToManyField(related_name='eventos_participados', to=settings.AUTH_USER_MODEL),
        ),
    ]
