# Generated by Django 4.2.16 on 2025-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0005_remove_evento_autores_alter_evento_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarcterEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_caracter_evento', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
