# Generated by Django 4.2.16 on 2025-04-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0006_carcterevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='idioma',
            field=models.CharField(choices=[('Espanol', 'Espanol'), ('Ingles', 'Ingles'), ('Portugues', 'Portugues'), ('Otro', 'Otro')], default='Seleccione...', max_length=50),
        ),
        migrations.AddField(
            model_name='articulo',
            name='numero',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.proyecto'),
        ),
    ]
