# Generated by Django 4.2.16 on 2025-04-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0007_articulo_idioma_articulo_numero_articulo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.area'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.departamento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
