# Generated by Django 4.2.16 on 2025-04-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigador', '0008_alter_evento_area_alter_evento_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.area'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_create',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.proyecto'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
