# Generated by Django 4.2.16 on 2025-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0010_revista_libro_conferencia_articulo_cita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revista_libro_conferencia',
            options={'verbose_name': 'Revista/Libro/Conferencia', 'verbose_name_plural': 'Revistas/Libros/Conferencias'},
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='idioma',
            field=models.CharField(blank=True, choices=[('Espanol', 'Espanol'), ('Ingles', 'Ingles'), ('Portugues', 'Portugues'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='issn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='pais',
            field=models.CharField(blank=True, choices=[('Cuba', 'Cuba'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
