# Generated by Django 4.2.16 on 2025-04-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0011_alter_revista_libro_conferencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='caracter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.carcterevento'),
        ),
    ]
