# Generated by Django 4.2.16 on 2025-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0012_alter_evento_caracter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='caracter',
            field=models.CharField(choices=[('Congreso', 'Congreso'), ('Jornada', 'Jornada'), ('Foro', 'Foro'), ('Conferencia', 'Conferencia'), ('Panel', 'Panel'), ('Simposio', 'Simposio'), ('Mesa Redonda', 'Mesa Redonda'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Convencion', 'Convencion'), ('Encuentro', 'Encuentro')], default='Seleccione...', max_length=50),
        ),
    ]
