# Generated by Django 4.2.16 on 2025-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0014_alter_evento_caracter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasesDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_base_datos', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('apellidos', models.CharField(max_length=50, unique=True)),
                ('orci', models.CharField(max_length=10)),
                ('google_academico', models.URLField(verbose_name='')),
                ('rgate', models.URLField(verbose_name='')),
            ],
        ),
    ]
