# Generated by Django 4.2.16 on 2025-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0016_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradores',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='google_academico',
            field=models.URLField(blank=True, verbose_name='Google Académico'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='orci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rgate',
            field=models.URLField(blank=True, verbose_name='ResearchGate'),
        ),
        migrations.AlterUniqueTogether(
            name='colaboradores',
            unique_together={('nombre', 'apellidos')},
        ),
    ]
