# Generated by Django 4.2.16 on 2025-05-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0018_alter_perfil_cargo'),
    ]

    operations = [
    ]
