# Generated by Django 4.2.16 on 2025-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0019_fix_cargo_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
