# Generated by Django 4.2.16 on 2025-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0021_alter_perfil_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesdatos',
            name='grupo',
            field=models.CharField(choices=[('Grupo 1', 'Grupo 1'), ('Grupo 2', 'Grupo 2'), ('Grupo 3', 'Grupo 3'), ('Grupo 4', 'Grupo 4')], default='Seleccione...', max_length=50),
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
