# Generated by Django 4.2.16 on 2025-05-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0022_basesdatos_grupo_revista_libro_conferencia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='index',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.basesdatos'),
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='cita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='index',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.basesdatos'),
        ),
    ]
