# Generated by Django 4.2.16 on 2025-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0023_articulo_index_revista_libro_conferencia_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Eventos/'),
        ),
    ]
