# Generated by Django 4.2.16 on 2025-05-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0025_modalidad_provincia_tipoevento_eventobase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventobase',
            options={'ordering': ['titulo'], 'verbose_name': 'Evento Base', 'verbose_name_plural': 'Eventos Base'},
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='institucion_responsable',
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.eventobase', verbose_name='Evento Base'),
        ),
        migrations.AddField(
            model_name='eventobase',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventobase',
            name='institucion',
            field=models.CharField(default=None, max_length=200, verbose_name='Institución responsable'),
        ),
        migrations.AddField(
            model_name='eventobase',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipoevento'),
        ),
        migrations.AddField(
            model_name='eventobase',
            name='titulo',
            field=models.CharField(default=None, max_length=200, verbose_name='Título del evento'),
        ),
        migrations.AlterField(
            model_name='eventobase',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventobase',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
