# Generated by Django 4.2.16 on 2025-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0026_alter_eventobase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='institucion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución responsable'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='evento',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
