# Generated by Django 4.2.16 on 2025-05-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0027_evento_institucion_evento_pais_evento_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='caracter',
        ),
        migrations.AddField(
            model_name='evento',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.modalidad'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre_ponencia',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.proyecto'),
        ),
        migrations.AddField(
            model_name='eventobase',
            name='isbn',
            field=models.CharField(default=111111111111111111111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventobase',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.modalidad'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, help_text='Seleccione cualquier día del mes, solo se considerará el mes y año', null=True, verbose_name='Fecha (Mes/Año)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipoevento'),
        ),
        migrations.AlterField(
            model_name='eventobase',
            name='provincia',
            field=models.CharField(blank=True, choices=[('PRI', 'Pinar del Río'), ('ART', 'Artemisa'), ('HAB', 'La Habana'), ('MAY', 'Mayabeque'), ('MTZ', 'Matanzas'), ('CFG', 'Cienfuegos'), ('VCL', 'Villa Clara'), ('SSP', 'Sancti Spíritus'), ('CAV', 'Ciego de Ávila'), ('CMG', 'Camagüey'), ('LTU', 'Las Tunas'), ('HOL', 'Holguín'), ('GRA', 'Granma'), ('SCU', 'Santiago de Cuba'), ('GTM', 'Guantánamo'), ('IJV', 'Isla de la Juventud')], max_length=3, null=True, verbose_name='Provincia'),
        ),
    ]
