# Generated by Django 4.2.16 on 2025-05-21 00:12

from django.db import migrations, models
import investigador.models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0028_remove_evento_caracter_evento_modalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='pag',
            field=models.CharField(blank=True, help_text='Formato: numero-numero (ej. 12-34)', max_length=20, null=True, validators=[investigador.models.validate_pag_format]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='provincia',
            field=models.CharField(blank=True, choices=[('PRI', 'Pinar del Río'), ('ART', 'Artemisa'), ('HAB', 'La Habana'), ('MAY', 'Mayabeque'), ('MTZ', 'Matanzas'), ('CFG', 'Cienfuegos'), ('VCL', 'Villa Clara'), ('SSP', 'Sancti Spíritus'), ('CAV', 'Ciego de Ávila'), ('CMG', 'Camagüey'), ('LTU', 'Las Tunas'), ('HOL', 'Holguín'), ('GRA', 'Granma'), ('SCU', 'Santiago de Cuba'), ('GTM', 'Guantánamo'), ('IJV', 'Isla de la Juventud')], max_length=3, null=True, verbose_name='Provincia'),
        ),
    ]
