# Generated by Django 4.2.16 on 2025-05-26 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigador', '0030_alter_colaboradores_options_colaboradores_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista_libro_conferencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revistas_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
