# Generated by Django 4.2.16 on 2025-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0031_revista_libro_conferencia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='idioma',
            field=models.CharField(blank=True, choices=[('Espanol', 'Espanol'), ('Ingles', 'Ingles'), ('Portugues', 'Portugues'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
