# Generated by Django 4.2.16 on 2025-05-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0032_articulo_url_alter_articulo_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
