# Generated by Django 4.2.16 on 2025-05-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0033_evento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
