# Generated by Django 4.2.16 on 2025-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0034_alter_evento_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='url',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, help_text='Seleccione cualquier día del mes, solo se considerará el mes y año', null=True, verbose_name='Fecha (Mes/Año)'),
        ),
    ]
