# Generated by Django 4.2.16 on 2025-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0035_remove_evento_url_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
