# Generated by Django 4.2.16 on 2025-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0036_evento_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='Eventos/'),
        ),
    ]
