# Generated by Django 4.2.16 on 2025-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0037_premio_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='cita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
