# Generated by Django 4.2.16 on 2025-06-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0038_alter_revista_libro_conferencia_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.CharField(max_length=50),
        ),
    ]
