# Generated by Django 4.2.16 on 2025-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0039_alter_articulo_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cita',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
