# Generated by Django 4.2.16 on 2025-06-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0040_alter_articulo_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigador.revista_libro_conferencia'),
        ),
    ]
