# Generated by Django 4.2.16 on 2025-06-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigador', '0041_articulo_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Línea de Investigación',
                'verbose_name_plural': 'Líneas de Investigación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SectorEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector Estratégico',
                'verbose_name_plural': 'Sectores Estratégicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoParticipacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Participación',
                'verbose_name_plural': 'Tipos de Participación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Programa',
                'verbose_name_plural': 'Tipos de Programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['-fecha_create'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AddField(
            model_name='programa',
            name='entidad_ejecutora',
            field=models.CharField(blank=True, max_length=150, verbose_name='Entidad ejecutora principal'),
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='programa',
            name='organismo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Organismo ejecutor'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='cantidad_expertos_contratados',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de expertos contratados'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='cantidad_expertos_otras_entidades',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de expertos de otras entidades'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='cantidad_expertos_uho',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de expertos de la UHO'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='cantidad_proyectos_programa',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de proyectos del programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo_programa',
            field=models.CharField(max_length=36, unique=True, verbose_name='Código único del programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_create',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.RemoveField(
            model_name='programa',
            name='jefe_programa',
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre_programa',
            field=models.CharField(max_length=255, verbose_name='Nombre del programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vicerrector responsable'),
        ),
        migrations.CreateModel(
            name='ParticipacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateField(auto_now_add=True, verbose_name='Fecha de incorporación')),
                ('activo', models.BooleanField(default=True, verbose_name='Participación activa')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.programa', verbose_name='Programa')),
                ('tipo_participacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipoparticipacion', verbose_name='Tipo de participación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario participante')),
            ],
            options={
                'verbose_name': 'Participación en Programa',
                'verbose_name_plural': 'Participaciones en Programas',
                'unique_together': {('programa', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='participantes_uho',
            field=models.ManyToManyField(blank=True, related_name='programas_participando', through='investigador.ParticipacionPrograma', to=settings.AUTH_USER_MODEL, verbose_name='Participantes de la UHO'),
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo_programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipoprograma', verbose_name='Tipo de programa'),
        ),
        migrations.AddField(
            model_name='programa',
            name='jefe_programa',
            field=models.ManyToManyField(related_name='jefe_programa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='linea_investigacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.lineainvestigacion', verbose_name='Línea de investigación UHO'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='sector_estrategico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.sectorestrategico', verbose_name='Sector estratégico'),
        ),
    ]
