# Generated by Django 4.2.16 on 2025-06-05 07:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigador', '0042_lineainvestigacion_sectorestrategico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_entidad', models.CharField(choices=[('Universidad', 'Universidad'), ('Instituto', 'Instituto de Investigación'), ('Centro', 'Centro de Investigación'), ('Empresa', 'Empresa'), ('Ministerio', 'Ministerio'), ('Hospital', 'Hospital/Centro de Salud'), ('ONG', 'Organización No Gubernamental'), ('Internacional', 'Organización Internacional'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('pais', models.CharField(default='Cuba', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entidad Participante',
                'verbose_name_plural': 'Entidades Participantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipoprograma',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Programa', 'verbose_name_plural': 'Tipos de Programa'},
        ),
        migrations.RemoveField(
            model_name='programa',
            name='area',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='cantidad_expertos_contratados',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='cantidad_expertos_otras_entidades',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='cantidad_expertos_uho',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='cantidad_proyectos_programa',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='participantes_uho',
        ),
        migrations.RemoveField(
            model_name='tipoprograma',
            name='sigla',
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sectorestrategico',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipoprograma',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lineainvestigacion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='participacionprograma',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participacionprograma',
            name='fecha_incorporacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participacionprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='investigador.programa'),
        ),
        migrations.AlterField(
            model_name='participacionprograma',
            name='tipo_participacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investigador.tipoparticipacion', verbose_name='Tipo de Participación'),
        ),
        migrations.AlterField(
            model_name='participacionprograma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo_programa',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe contener solo letras mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='entidad_ejecutora',
            field=models.CharField(max_length=200, verbose_name='Entidad Ejecutora'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.RemoveField(
            model_name='programa',
            name='jefe_programa',
        ),
        migrations.AlterField(
            model_name='programa',
            name='linea_investigacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investigador.lineainvestigacion', verbose_name='Línea de Investigación de la UHO'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre_programa',
            field=models.CharField(max_length=300, verbose_name='Nombre del Programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='organismo',
            field=models.CharField(max_length=200, verbose_name='Organismo'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='sector_estrategico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investigador.sectorestrategico', verbose_name='Sector Estratégico'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipo_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investigador.tipoprograma', verbose_name='Tipo de Programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='sectorestrategico',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ProgramaEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.entidadparticipante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.programa')),
            ],
            options={
                'verbose_name': 'Programa-Entidad',
                'verbose_name_plural': 'Programa-Entidades',
                'unique_together': {('programa', 'entidad')},
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='entidades_participantes',
            field=models.ManyToManyField(blank=True, through='investigador.ProgramaEntidad', to='investigador.entidadparticipante', verbose_name='Entidades Participantes'),
        ),
        migrations.AddField(
            model_name='programa',
            name='jefe_programa',
            field=models.CharField(default=1, max_length=200, verbose_name='Jefe del Programa'),
            preserve_default=False,
        ),
    ]
