# Generated by Django 4.2.16 on 2025-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0043_entidadparticipante_alter_tipoprograma_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='aprobacion',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50, null=True),
        ),
    ]
