# Generated by Django 4.2.16 on 2025-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0044_alter_articulo_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='numero',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
