# Generated by Django 5.2 on 2025-07-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0045_alter_articulo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.area'),
        ),
    ]
