# Generated by Django 5.2 on 2025-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0047_programa_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='caracter_premio',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='premio',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
