# Generated by Django 5.2 on 2025-07-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0048_alter_premio_caracter_premio_alter_premio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='caracter_premio',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Seleccione...'),
        ),
    ]
