# Generated by Django 5.2 on 2025-07-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0049_alter_premio_caracter_premio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Premio')),
                ('institucion', models.TextField(blank=True, null=True, verbose_name='Institución que lo otorga')),
            ],
            options={
                'verbose_name': 'Tipo de Premio',
                'verbose_name_plural': 'Tipos de Premios',
                'ordering': ['nombre'],
            },
        ),
    ]
