# Generated by Django 5.2 on 2025-07-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0050_tipopremio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopremio',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institución que lo otorga'),
        ),
        migrations.AlterField(
            model_name='tipopremio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Tipo de Premio'),
        ),
    ]
