# Generated by Django 5.2 on 2025-07-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0051_alter_tipopremio_institucion_alter_tipopremio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipopremio'),
        ),
    ]
