# Generated by Django 5.2 on 2025-07-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0052_alter_premio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipopremio'),
        ),
    ]
