# Generated by Django 5.2 on 2025-07-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0053_alter_premio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
