# Generated by Django 5.2 on 2025-07-05 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0054_alter_premio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.tipopremio'),
        ),
    ]
