# Generated by Django 5.2 on 2025-07-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0055_alter_premio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='Premios/'),
        ),
    ]
