# Generated by Django 5.2 on 2025-07-06 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0056_alter_premio_diploma'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracterPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Caracter de Premio')),
            ],
            options={
                'verbose_name': 'Tipo de Premio',
                'verbose_name_plural': 'Tipos de Premios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='premio',
            name='area',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='caracter_premio',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='fecha_create',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='url',
        ),
        migrations.AlterField(
            model_name='tipopremio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Tipo de Premio'),
        ),
        migrations.AddField(
            model_name='premio',
            name='caracter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investigador.caracterpremio'),
            preserve_default=False,
        ),
    ]
