# Generated by Django 5.2 on 2025-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0057_caracterpremio_remove_premio_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracterpremio',
            options={'ordering': ['nombre'], 'verbose_name': 'Carácter de Premio', 'verbose_name_plural': 'Carácteres de Premios'},
        ),
        migrations.RenameField(
            model_name='premio',
            old_name='fecha',
            new_name='fecha_create',
        ),
    ]
