# Generated by Django 5.2 on 2025-07-08 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0058_alter_caracterpremio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.area'),
        ),
        migrations.AddField(
            model_name='premio',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.departamento'),
        ),
    ]
