# Generated by Django 5.2 on 2025-07-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0059_premio_area_premio_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='proyecto',
            field=models.ManyToManyField(blank=True, null=True, related_name='proyectos_a_los_que_pertenece', to='investigador.proyecto'),
        ),
    ]
