# Generated by Django 5.2 on 2025-07-26 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0061_institucion_alter_premio_titulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colaboradores',
            new_name='Colaborador',
        ),
    ]
