# Generated by Django 5.2 on 2025-07-26 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0062_rename_colaboradores_colaborador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='premiados',
        ),
        migrations.CreateModel(
            name='PremioPremiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigador.colaborador')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiados_set', to='investigador.premio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('premio', 'usuario', 'colaborador')},
            },
        ),
    ]
