# Generated by Django 5.2 on 2025-07-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0063_remove_premio_premiados_premiopremiado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterUniqueTogether(
            name='colaborador',
            unique_together=set(),
        ),
    ]
