# Generated by Django 5.2 on 2025-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0064_alter_colaborador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='proyecto',
            field=models.ManyToManyField(blank=True, related_name='proyectos_a_los_que_pertenece', to='investigador.proyecto'),
        ),
    ]
