# Generated by Django 5.2 on 2025-07-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0065_alter_perfil_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='proyecto',
            field=models.ManyToManyField(blank=True, to='investigador.proyecto'),
        ),
    ]
