# Generated by Django 5.2 on 2025-07-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0066_premio_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='premio',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.proyecto'),
        ),
    ]
