# Generated by Django 5.2 on 2025-07-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0067_remove_premio_proyecto_premio_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.institucion'),
        ),
    ]
