# Generated by Django 5.2 on 2025-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0068_premio_institucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Institucion', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterField(
            model_name='caracterpremio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Carácter de Premio'),
        ),
    ]
