# Generated by Django 5.2 on 2025-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0069_alter_institucion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='google_academico',
            field=models.URLField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='orci',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rgate',
            field=models.URLField(blank=True, verbose_name=''),
        ),
    ]
