# Generated by Django 5.2 on 2025-08-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0070_alter_perfil_google_academico_alter_perfil_orci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nombre_manual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_colaboradores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='usuario_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_de', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='colaborador',
            unique_together={('propietario', 'usuario_sistema', 'nombre_manual')},
        ),
    ]
