# Generated by Django 5.2 on 2025-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0071_alter_colaborador_options_colaborador_nombre_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, to='investigador.colaborador'),
        ),
    ]
