# Generated by Django 5.2 on 2025-08-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0072_premio_colaboradores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterUniqueTogether(
            name='colaborador',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='premio',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nombre_manual',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='usuario_sistema',
        ),
    ]
