# Generated by Django 5.2.4 on 2025-08-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0073_alter_colaborador_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='presencialidad',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='eventobase',
            name='modalidad',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_create',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investigador.institucion', verbose_name='Institución responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventobase',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.institucion', verbose_name='Institución responsable'),
        ),
        migrations.CreateModel(
            name='EventoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigador.colaborador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_set', to='investigador.evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'usuario', 'colaborador')},
            },
        ),
    ]
