# Generated by Django 5.2.4 on 2025-08-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0074_remove_evento_autores_remove_evento_colaboradores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='Eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='isbn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.modalidad'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pais',
            field=models.CharField(default=1, max_length=100, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipoevento'),
        ),
        migrations.AlterField(
            model_name='eventobase',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.tipoevento'),
        ),
    ]
