# Generated by Django 5.2 on 2025-09-07 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0075_alter_evento_certificado_alter_evento_isbn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasesDatos',
            new_name='Indexacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha_creacion',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='cita',
            new_name='forma_citar',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='index',
            new_name='indexacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='issn',
            new_name='issn_isbn',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_create',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Articulos/'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='idioma',
            field=models.CharField(blank=True, choices=[('Espanol', 'Espanol'), ('Ingles', 'Ingles'), ('Portugues', 'Portugues'), ('Otro', 'Otro')], default='Seleccione...', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigador.proyecto'),
        ),
        migrations.CreateModel(
            name='ArticuloAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_set', to='investigador.articulo')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigador.colaborador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('articulo', 'usuario', 'colaborador')},
            },
        ),
    ]
