# Generated by Django 5.2 on 2025-09-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0076_rename_basesdatos_indexacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha_publicacion',
            new_name='fecha_create',
        ),
    ]
