# Generated by Django 5.2.3 on 2025-09-27 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0077_rename_fecha_publicacion_articulo_fecha_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista_libro_conferencia',
            name='cita',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='issn_isbn',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Sólo se permiten números, letras y guiones', regex='^[0-9A-Za-z-]*$')]),
        ),
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Sólo se permiten números, letras y guiones', regex='^[0-9A-Za-z-]*$')]),
        ),
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='issn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Sólo se permiten números, letras y guiones', regex='^[0-9A-Za-z-]*$')]),
        ),
    ]
