# Generated by Django 5.2.3 on 2025-09-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0078_remove_revista_libro_conferencia_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista_libro_conferencia',
            name='idioma',
        ),
    ]
