# Generated by Django 5.2.3 on 2025-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0079_remove_revista_libro_conferencia_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
