# Generated by Django 5.2.3 on 2025-09-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0080_alter_revista_libro_conferencia_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='issn_isbn',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='issn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
