# Generated by Django 5.2 on 2025-11-11 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0081_alter_articulo_issn_isbn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprograma',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Programa', 'verbose_name_plural': 'Tipos de Programas'},
        ),
        migrations.RenameField(
            model_name='tipoprograma',
            old_name='codigo',
            new_name='sigla',
        ),
        migrations.RemoveField(
            model_name='lineainvestigacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='lineainvestigacion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='lineainvestigacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='sectorestrategico',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='sectorestrategico',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='sectorestrategico',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipoparticipacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipoparticipacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipoprograma',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipoprograma',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='issn_isbn',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='ISSN solo puede contener letras, números y guiones', regex='^[0-9A-Za-z-]*$')]),
        ),
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='ISSN solo puede contener letras, números y guiones', regex='^[0-9A-Za-z-]*$')]),
        ),
        migrations.AlterField(
            model_name='revista_libro_conferencia',
            name='issn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='ISSN solo puede contener letras, números y guiones', regex='^[0-9A-Za-z-]*$')]),
        ),
    ]
